config/routes.rb
Rails.application.routes.draw do
  resources :nums
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/num.rb
class Num < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nums_controller.rb
class NumsController < ApplicationController
  before_action :set_num, only: %i[ show edit update destroy ]

  # GET /nums or /nums.json
  def index
    @nums = Num.all
  end

  # GET /nums/1 or /nums/1.json
  def show
  end

  # GET /nums/new
  def new
    @num = Num.new
  end

  # GET /nums/1/edit
  def edit
  end

  # POST /nums or /nums.json
  def create
    @num = Num.new(num_params)

    respond_to do |format|
      if @num.save
        format.html { redirect_to @num, notice: "Num was successfully created." }
        format.json { render :show, status: :created, location: @num }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @num.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nums/1 or /nums/1.json
  def update
    respond_to do |format|
      if @num.update(num_params)
        format.html { redirect_to @num, notice: "Num was successfully updated." }
        format.json { render :show, status: :ok, location: @num }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @num.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nums/1 or /nums/1.json
  def destroy
    @num.destroy
    respond_to do |format|
      format.html { redirect_to nums_url, notice: "Num was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_num
      @num = Num.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def num_params
      params.require(:num).permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nums_helper.rb
module NumsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Numbers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nums/_form.html.erb
<%= form_with(model: num) do |form| %>
  <% if num.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(num.errors.count, "error") %> prohibited this num from being saved:</h2>

      <ul>
        <% num.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nums/edit.html.erb
<h1>Editing Num</h1>

<%= render 'form', num: @num %>

<%= link_to 'Show', @num %> |
<%= link_to 'Back', nums_path %>

app/views/nums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nums</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nums.each do |num| %>
      <tr>
        <td><%= num.number %></td>
        <td><%= link_to 'Show', num %></td>
        <td><%= link_to 'Edit', edit_num_path(num) %></td>
        <td><%= link_to 'Destroy', num, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Num', new_num_path %>

app/views/nums/new.html.erb
<h1>New Num</h1>

<%= render 'form', num: @num %>

<%= link_to 'Back', nums_path %>

app/views/nums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @num.number %>
</p>

<%= link_to 'Edit', edit_num_path(@num) %> |
<%= link_to 'Back', nums_path %>